### ISSUE TITLE
Requirements in Documentation

### ISSUE THREAD

**Issue by hydrochili** [exoclime/HELIOS-K#10]
There is a typo in the documentation.
Under the requirements of 'nist_Lines2.py' in 'HELIOS-K/docs/helios_k/compilation.rst' 'csh' is listed as a requirement.
However, the python file needs 'csv'.
Since 'csh' is an existing package a fix would be nice to avoid confusion.

**Comment by sigrimm** [comment]
Thank for spotting the typo, it is corrected now.
