### ISSUE TITLE
What is `x` in the resampling script

### ISSUE THREAD

**Issue by Nicholaswogan** [exoclime/HELIOS-K#11]
What is `x` in the resampling script? It isn't defined earlier in the script

https://github.com/exoclime/HELIOS-K/blame/master/docs/helios_k/resampling.rst#L77

**Comment by Nicholaswogan** [comment]
Looks like `x` is just an array between 0 and 1: `np.linspace(0,1,100)`. Can you add this to the docs

**Comment by sigrimm** [comment]
Yes, x is an array between 0 and 1, containing n points, where n corresponds to the number of points per bin. 
I added it to the documentation, and refer also to the code tools/recon_bin.py which contains a working function.
