### ISSUE TITLE
Pressure is in atm and not bar?

### ISSUE THREAD

**Issue by Nicholaswogan** [exoclime/HELIOS-K#12]
The [docs](https://helios-k.readthedocs.io/en/latest/helios_k/heliosk.html) say that the pressure in `param.dat` are in atmospheres. I just want to confirm that pressure is actually in atmospheres, and not in bars.

If input pressure is in atmospheres, can you update the relevant line in the docs to be more explicit, including a link to the wiki page on standard atmospheres:

> P: Pressure in [Standard Atmospheres](https://en.wikipedia.org/wiki/Standard_atmosphere_(unit))

Just seems like a units mistake I'm and other are bound to make. Many think in bars, and not Standard Atmospheres.

**Comment by sigrimm** [comment]
Hi,
Yes, I confirm that pressure must be given in atmospheres (atm) as written in the documentation.
I have updated the documentation to be more explicit about this and included the link you suggested. 

Thanks for pointing out this potential uncertainty. 

Simon
