### ISSUE TITLE
GPU returns `invalid configuration argument`

### ISSUE THREAD

**Issue by Nicholaswogan** [exoclime/HELIOS-K#16]
When I try using the `binsFile` option, trying to reproduce the example in the docs, I get the following error from the GPU

```
Kb error = 9 = invalid configuration argument
```

my param.dat file:

```
name = i
T = 100.0
P = 1.0
PFile = -
Species Name = 01_hit16
SpeciesFile = -
ciaSystem = -
pathToData = data/
numin = 0.0
numax = 1000.0
dnu = 0.001
Nnu per bin = 0
cutMode = 0
cut = 25.0
doResampling = 0
nC = 20
doTransmission = 0
nTr = 1000
dTr = 0.05
doStoreFullK = 1
pathToK =
doStoreSK = 2
nbins = 5
binsFile = bins.dat
OutputEdgesFile = edges.dat
kmin = 0.0
qalphaL = 1.0
gammaF = 1.0
doMean = 0
Units = 0
ReplaceFiles = 1
profile = 1
subLorentzianfile = -
removePlinth = 0
doTuning = 1
```

My `bins.dat` and `edges.dat` are identical to the examples docs.

**Comment by Nicholaswogan** [comment]
Ahh there is an issue in the docs. You say that the bins file should have the format

```
bins.dat
--------
2000
6000
12000
15000
25000
30000
```

However, the header involving `bins.dat` and the `-----` is not actually allowed. The same is true with the edges file

```
edges.dat
---------
0.0
0.1
0.45
0.78
1.0
```

The header should not actually be there. It should just be the numbers.

**Comment by sigrimm** [comment]
Thank you for pointing out this. I updated the documentation, and it should be now more clear. The headers belong not into the files.
